// electron/types/crag.ts
// Shared interfaces for the CRAG pgvector pipeline.

import { Pool } from "pg";

// ─── Chunk Representation ────────────────────────────────────────────────────

/**
 * Represents a single semantic chunk extracted from a notes file,
 * ready to be inserted into the `knowledge_chunks` Postgres table.
 */
export interface KnowledgeChunk {
  /** Deterministic ID, e.g. "notes1_s3_c2" (source file, section index, chunk index) */
  id: string;
  /** Human-readable section heading derived from the `---` delimiter split. */
  section: string;
  /** Auto-extracted topic keywords for keyword search boosting. */
  topics: string[];
  /** The cleaned text content (citation tags stripped). */
  content: string;
  /** Extracted citation tag numbers, e.g. [7, 0] from 【7:0†source】 */
  sourceTags: number[];
  /** The source file this chunk was parsed from. */
  sourceFile: string;
}

/**
 * Extends KnowledgeChunk with the 768-dim embedding vector
 * generated by Gemini `text-embedding-004`.
 */
export interface EmbeddedChunk extends KnowledgeChunk {
  embedding: number[];
}

// ─── Retrieval Results ───────────────────────────────────────────────────────

/** A single result row returned by a pgvector similarity search. */
export interface RetrievalResult {
  id: string;
  section: string;
  topics: string[];
  content: string;
  sourceTags: number[];
  sourceFile: string;
  /** 1 - cosine_distance. Higher is more similar (0..1). */
  similarityScore: number;
  /** Full-text-search rank (ts_rank). May be 0 if FTS found no match. */
  ftsRank: number;
  /** Weighted combination: α * ftsRank_norm + (1-α) * similarityScore */
  hybridScore: number;
}

// ─── Evaluator ───────────────────────────────────────────────────────────────

export interface EvaluationResult {
  chunkId: string;
  relevanceScore: number; // 1-5
  reason: string;
}

export type EvaluationVerdict = "CORRECT" | "AMBIGUOUS" | "INCORRECT";

// ─── Configuration ───────────────────────────────────────────────────────────

export interface PostgresConfig {
  host: string;
  port: number;
  user: string;
  password: string;
  database: string;
  /** Max connections in the pool. Default 5 for an Electron desktop app. */
  maxPoolSize: number;
}

export interface CragConfig {
  enabled: boolean;
  topK: number;
  /** Minimum hybrid score to include a chunk in results. */
  minRelevanceThreshold: number;
  /** Evaluator score threshold. ≥ this → CORRECT. */
  evaluationThreshold: number;
  maxCorrectionRounds: number;
  /**
   * Hybrid search alpha.
   *   0.0 = pure semantic (pgvector cosine)
   *   1.0 = pure keyword (Postgres FTS)
   *   0.3 = recommended default (favor semantic, fall back to keywords)
   */
  retrievalAlpha: number;
  /** Paths to notes files relative to the project root. */
  notesPaths: string[];
  enableQueryCache: boolean;
  queryCacheSize: number;
  postgres: PostgresConfig;
}

// ─── Pool Holder ─────────────────────────────────────────────────────────────

/**
 * Dependency injection container passed from main.ts into
 * NotesChunker, Retriever, Evaluator, etc.
 */
export interface CragDeps {
  pool: Pool;
  geminiApiKey: string;
  cragConfig: CragConfig;
}
